<?php header('Content-Type: text/html; charset=UTF-8') ?>
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN">
<title>Choices – UBU Cult TV Society</title>
<link rel=stylesheet type="text/css" href="../../style.css">

<div id=container>
  <div id=header>
    <h1>Choices by Thomas Cave</h1>
    <p id=breadcrumbs><a href="../../">UBU Cult TV</a> → <a href="../">Fanart</a> → Choices
  </div>

  <div id=content>
    <p class=sec>Disclaimer: I do not own "Lord Vader" "Coruscant" "His Royal Highness Emperor Palpatine" or any of the other Star Wars characters, objects or concepts mentioned in this Speech, they are all property of someone else, probably George Lucas and or Lucasfilm.ltd. The rest is mine, although that dose not leave me with much.
    <p>Setting The Scene: The following piece of text is a speech given to the highest-ranking members of Emperor Palpatine's regime, Civil and Military, by an unknown Imperial Servant. It is being delivered, shortly (several days) after the events recorded in Return Of The Jedi, on Coruscant, or in a Space Station, Moon Base or Capital Military Vessel orbiting Coruscant.
    <p>Ladies and Gentlemen, Fleet and Army Commanders, Governors of the Core Systems; welcome to Coruscant. I have just been informed of the destruction of the Imperial Space Navy’s second moon base battle station, the death of Lord Vader and His Royal Highness Emperor Palpatine.
    <p>I think it is plain to see that the Rebels believe this cowardly act will throw the Empire into chaos, I believe that they are mistaken. However this situation does bring us to a crossroads. A place that requires us to ask a few key questions: Where are we going? What will we find when we get there?
    <p>We are heading for a fall, at the end of which we will find death, unless we change direction. The behavior of our August Emperor and his ever present lapdog Vader has brought the Empire to it’s knees, driving more and more worlds and individuals into the arms of the Rebels. Vader’s personal power trips and quests for revenge did far more good than harm, from the Alliances point of view. If we continue to allow certain, nameless, Imperial servants, both Military and Civil, to use violence and repression, openly, as though they were a sledge hammer the Rebels will be victorious and it will be the end of everyone in this room!
    <p>I am not suggesting that we should give up and go home, I am merely suggesting that we consider our actions more carefully.
    <p>Let us discuss some Imperial policies in greater detail, conscription. If we do not get a sufficient number of volunteers for Imperial Army or Navy service then we conscript the minimum number required, something we have had to increasingly resort to of late. This is both unwise and unnecessary, does anybody in this room think that forcibly drafting members of the galaxies angst ridden, apathetic youth into military service will endear us to the friends and family they leave behind? Did Palpatine or Vader ever stop to wonder why Rebel volunteers have increased exponentially over the past ten years? No doubt many of you are thinking that this form of top up conscription is unfortunate, but necessary. I conjecture that you are mistaken, that if we did not follow such policies and sought to persuade rather than coerce we would always have a sufficient number of volunteers. Partly because the number of volunteers would increase, partly because we would no longer need such a huge number of them, but mostly because we would not lose as many as we do at present, which would serve to encourage more of our young to sign up for duty.
    <p>If Vader or Palpatine were here, I would be dead by now, my larynx and trachea would have been crushed before I could utter the word "lapdog" allowing me to join the cadaverous ranks of so many other dedicated Imperial servants who have dared to criticize or displease. Many of these people were personal friends of mine; many of the people in this room could say the same thing.
    <p>It is no wonder that the Imperial Navy is not as effective as it used to be. The reason for this has nothing to do with some kind of mystical Force related, psycho assistance, that Palpatine was giving us, when he could be bothered to turn up and watch us fight and die for him. It was a swift turnover of high-ranking Officers in the Army and Navy that has created this shortfall. A swift turnover, mainly, produced by the insane, force blurred, blood lust blunders of Vader and the almost blasé attitude of Palpatine.
    <p>In a perverse turn of fate I think that the Alliance has done us a potential courtesy. Both Vader and Palpatine are dead; the greater part of their odd, unnatural, retinue of attendants is also dead. We are presented with absolute, unchallenged, power over the Empire and Imperial business; we have what is often referred to as a "Historic Opportunity" to change the Empire so that it may endure.
    <p>A military victory over the Alliance is unrealistic. You could execute a million Rebels and knockout a thousand Rebel Bases, but one backward Rebel outpost would always escape the purge by its sheer lack of importance. This smidgen of cancer would regroup and begin to grow again. Before you could discover your omission, the Alliance would return, more galling than before. You would then have to execute two million Rebels and knockout two thousand Rebel Bases. And then it would only begin again.
    <p>The only way to crush the Alliance is by Political, rather than Military, strategy. We must begin what you could call the perceived democratization of the Empire. This would mean, in reality, assigning the more mundane aspects of our legislative power to democratic or semi-democratic institutions. This way we could make the Empire appear more democratic without altering the balance of power within it.
    <p>Without the tacit support that the Rebels enjoy from many Imperial citizens, and the open support that they enjoy from Imperial subjects, humans and Aliens alike, they would fade away into the sands of time. The Rebels would be unlikely to retain this support if we ceased to appear tyrannical, as we do at present.
    <p>The choice is simple pretend to change and survive, stay rigidly the same and crumble. Note well before you chose, crumbling would mean our deaths and ultimately the ignominy of humans becoming just another race with a few seats in the New Republic Senate. Before the whole thing degenerated into chaos, of course. In the name of the Empire, thank you for your attention.
  </div>
</div>
